server:
  port: 8080

logging:
  level:
    root: INFO
    com.egemsoft.application.rickandmortyapi: DEBUG
ms:
  root:
    url: /v1/rickandmortyapi/api
  full:
    url: http://localhost:8080/v1/rickandmortyapi/api

client:
  rickandmortyapi:
    url: https://rickandmortyapi.com/api

feign:
  httpclient:
    disable-ssl-validation: true

pagination:
  countLimit: 20

spring:
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

