server:
  port: 8080

logging:
  level:
    root: INFO
    com.egemsoft.application.rickandmortyapi: DEBUG
ms:
  root:
    url: /v1/rickandmortyapi
  full:
    url: http://localhost:8080/v1/rickandmortyapi

client:
  rickandmortyapi:
    url: https://rickandmortyapi.com/api

feign:
  httpclient:
    disable-ssl-validation: true

pagination:
  limit: 20


